import Validator from './core/validatorDecorator';
import { isObject, isBuiltInComponent } from './utils';
import { resolveConfig, setConfig } from './config';
import { getValidator } from './state';

/**
 * Vue 3 mixin: provides $validator to children, injects errors/fields, and cleans up on unmount.
 */

/**
 * Returns whether the component requested $validator via inject.
 *
 * @param {Record<string, unknown> | string[]} injections - Component inject option.
 * @returns {boolean}
 */
const requestsValidator = (injections: Record<string, unknown> | string[]) => {
  if (isObject(injections) && (injections as Record<string, unknown>).$validator) {
    return true;
  }
  return false;
};

/**
 * Returns the Vue instance uid (Vue 3: vm.$.uid, fallback: vm._uid).
 *
 * @param {import('vue').ComponentInternalInstance | { $: { uid: number }, _uid: number }} vm - Component instance.
 * @returns {number | undefined}
 */
function getInstanceUid (vm) {
  return (vm.$ && vm.$.uid !== undefined) ? vm.$.uid : vm._uid;
}

/**
 * Vue 3 mixin: provides $validator to children, injects $validator/errors/fields, and cleans up on unmount.
 * Applied globally when using app.use(Formward).
 */
export default {
  /** Provide $validator to descendant components. */
  provide () {
    if (this.$validator && !isBuiltInComponent(this)) {
      return {
        $validator: this.$validator
      };
    }

    return {};
  },
  beforeCreate () {
    // if built in do nothing.
    if (isBuiltInComponent(this) || this.$options.$__formuleInject === false) {
      return;
    }

    // if its a root instance set the config if it exists.
    if (!this.$parent) {
      setConfig(this.$options.$_formule || {});
    }

    const options = resolveConfig(this);

    // if its a root instance, inject anyways, or if it requested a new instance.
    if (!this.$parent || (this.$options.$_formule && /new/.test(this.$options.$_formule.validator))) {
      this.$validator = new Validator(getValidator(), this);
    }

    const requested = requestsValidator(this.$options.inject);

    // if automatic injection is enabled and no instance was requested.
    if (! this.$validator && options.inject && !requested) {
      this.$validator = new Validator(getValidator(), this);
    }

    // Vue 3: ensure every component gets a validator when inject is enabled (e.g. parent provide failed or $parent chain broken).
    if (!this.$validator && options.inject) {
      this.$validator = new Validator(getValidator(), this);
    }

    // don't inject errors or fieldBag as no validator was resolved.
    if (!requested && !this.$validator) {
      return;
    }

    // Vue 3: reactivity is handled via computed; no defineReactive needed.
    if (!requested && this.$validator) {
      // validator.errors is already referenced by computed below
    }

    if (!this.$options.computed) {
      this.$options.computed = {};
    }

    this.$options.computed[options.errorBagName || 'errors'] = function errorBagGetter () {
      const bag = this.$validator.errors;
      if (bag && bag.items) bag.items.slice();
      return bag;
    };
    this.$options.computed[options.fieldsBagName || 'fields'] = function fieldBagGetter () {
      return this.$validator.fields.items.reduce((acc, field) => {
        if (field.scope) {
          if (!acc[`$${field.scope}`]) {
            acc[`$${field.scope}`] = {};
          }

          acc[`$${field.scope}`][field.name] = field.flags;

          return acc;
        }

        acc[field.name] = field.flags;

        return acc;
      }, {});
    };
  },
  beforeUnmount () {
    if (this.$validator && getInstanceUid(this) === this.$validator.id) {
      this.$validator.errors.clear(); // remove errors generated by this component.
    }
  }
};
